# file: roles/common/tasks/main.yml

- name: Update the package list
  apt: update_cache=yes

- name: Install automatic security updates
  command: /usr/bin/unattended-upgrade

- name: Install htop
  apt: pkg=htop

- name: Setup vimrc
  copy: src=vimrc.local dest=/etc/vim/vimrc.local
