# file: roles/common/tasks/main.yml

- name: Update the package list
  apt: update_cache=yes

- name: Install automatic security updates
  command: /usr/bin/unattended-upgrade

- name: Install htop
  apt: pkg=htop
